# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/librodigital_academic
spring.datasource.username=postgres
spring.datasource.password=monsalve1974

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Puerto (para no chocar con auth)
server.port=8082
